import type { MetadataRoute } from 'next';
import { createClient } from '@/lib/supabase/server';
import { VIBES, NEIGHBORHOODS, PLACE_TYPES } from '@/lib/taxonomy';

// Sitemap autogenerated from public itineraries + the static marketing pages.
// Refreshes hourly via the route's default revalidation. Submit at
// https://search.google.com/search-console for crawl bootstrapping.

const SITE = 'https://after5.app';

export const revalidate = 3600;

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const supabase = await createClient();
  const { data } = await supabase
    .from('itineraries')
    .select('slug, generated_at')
    .eq('is_public', true)
    .not('slug', 'is', null)
    .order('generated_at', { ascending: false });

  const rows = (data ?? []) as Array<{ slug: string; generated_at: string | null }>;
  const dateUrls: MetadataRoute.Sitemap = rows.map((row) => ({
    url: `${SITE}/dates/${row.slug}`,
    lastModified: row.generated_at ? new Date(row.generated_at) : new Date(),
    changeFrequency: 'monthly',
    priority: 0.7,
  }));

  // Aggregator pages — high SEO value because they target head/mid-tail
  // queries ("romantic kelowna date", "best wineries in kelowna").
  const vibeUrls: MetadataRoute.Sitemap = VIBES.map((v) => ({
    url: `${SITE}/vibes/${v.slug}`,
    changeFrequency: 'weekly',
    priority: 0.8,
  }));
  const neighborhoodUrls: MetadataRoute.Sitemap = NEIGHBORHOODS.map((n) => ({
    url: `${SITE}/neighborhoods/${n.slug}`,
    changeFrequency: 'weekly',
    priority: 0.8,
  }));
  const typeUrls: MetadataRoute.Sitemap = PLACE_TYPES.map((t) => ({
    url: `${SITE}/types/${t.slug}`,
    changeFrequency: 'weekly',
    priority: 0.8,
  }));

  // Pull live places + modifiers + templates for their detail pages.
  const [{ data: places }, { data: modifiers }, { data: templates }] = await Promise.all([
    supabase
      .from('places')
      .select('slug, updated_at')
      .eq('is_active', true)
      .eq('approval_status', 'live')
      .not('slug', 'is', null),
    supabase.from('modifiers').select('id').eq('is_active', true),
    supabase.from('templates').select('id, created_at').eq('is_active', true),
  ]);
  const placeUrls: MetadataRoute.Sitemap = (places ?? []).map((p: any) => ({
    url: `${SITE}/places/${p.slug}`,
    lastModified: p.updated_at ? new Date(p.updated_at) : new Date(),
    changeFrequency: 'monthly',
    priority: 0.7,
  }));
  const wowUrls: MetadataRoute.Sitemap = (modifiers ?? []).map((m: any) => ({
    url: `${SITE}/wow/${m.id}`,
    changeFrequency: 'monthly',
    priority: 0.5,
  }));
  const templateUrls: MetadataRoute.Sitemap = (templates ?? []).map((t: any) => ({
    url: `${SITE}/templates/${t.id}`,
    lastModified: t.created_at ? new Date(t.created_at) : new Date(),
    changeFrequency: 'monthly',
    priority: 0.5,
  }));

  return [
    { url: `${SITE}/`,              priority: 1.0, changeFrequency: 'weekly' },
    { url: `${SITE}/plan`,          priority: 0.9, changeFrequency: 'weekly' },
    { url: `${SITE}/dates`,         priority: 0.9, changeFrequency: 'daily'  },
    { url: `${SITE}/places`,        priority: 0.9, changeFrequency: 'weekly' },
    { url: `${SITE}/vibes`,         priority: 0.8, changeFrequency: 'weekly' },
    { url: `${SITE}/neighborhoods`, priority: 0.8, changeFrequency: 'weekly' },
    { url: `${SITE}/types`,         priority: 0.8, changeFrequency: 'weekly' },
    { url: `${SITE}/privacy`,       priority: 0.2, changeFrequency: 'yearly' },
    { url: `${SITE}/terms`,         priority: 0.2, changeFrequency: 'yearly' },
    ...vibeUrls,
    ...neighborhoodUrls,
    ...typeUrls,
    ...placeUrls,
    ...dateUrls,
    ...wowUrls,
    ...templateUrls,
  ];
}
