import type { MetadataRoute } from 'next';
import { createClient } from '@/lib/supabase/server';

// Sitemap autogenerated from public itineraries + the static marketing pages.
// Refreshes hourly via the route's default revalidation. Submit at
// https://search.google.com/search-console for crawl bootstrapping.

const SITE = 'https://after5.app';

export const revalidate = 3600;

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const supabase = await createClient();
  const { data } = await supabase
    .from('itineraries')
    .select('slug, generated_at')
    .eq('is_public', true)
    .not('slug', 'is', null)
    .order('generated_at', { ascending: false });

  const rows = (data ?? []) as Array<{ slug: string; generated_at: string | null }>;
  const dateUrls: MetadataRoute.Sitemap = rows.map((row) => ({
    url: `${SITE}/dates/${row.slug}`,
    lastModified: row.generated_at ? new Date(row.generated_at) : new Date(),
    changeFrequency: 'monthly',
    priority: 0.7,
  }));

  return [
    { url: `${SITE}/`,        priority: 1.0, changeFrequency: 'weekly' },
    { url: `${SITE}/plan`,    priority: 0.9, changeFrequency: 'weekly' },
    { url: `${SITE}/dates`,   priority: 0.9, changeFrequency: 'daily'  },
    { url: `${SITE}/privacy`, priority: 0.2, changeFrequency: 'yearly' },
    { url: `${SITE}/terms`,   priority: 0.2, changeFrequency: 'yearly' },
    ...dateUrls,
  ];
}
